routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Resources\CompanyResource;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::resource('company', CompanyController::class)->middleware('auth');

Route::post('/companyData', [CompanyController::class,'data'])->middleware('auth')->name('data');


require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class company extends Model
{
    use HasFactory;

    protected $guarded = [];

}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $request->validate([
            'name' => 'required|min:5',
            'email' => 'required|email',
            'logo' => 'required|mimes:png',
            'link' => 'required|url'

        ]);

        if($request->hasFile('logo')){
            
            $filename = $request->name.'.'.$request->file('logo')->getClientOriginalExtension();
            $request->logo =  $filename;
            
            $file = $request->file('logo');
            $file->move('uploads/', $filename);
            
        }else{
            
            $request->logo = '';
        }

        company::create([
            'name' => $request->name,
            'email' => $request->email,
            'link' => $request->link,
            'logo' => $request->logo,
        ]);

        return redirect(route('company.index'))->with('success', 'Data company telah berjaya dimuat-naik');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function data(Request $req)
    {
        $data = company::all();

        return $data;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = company::where('id',$id)->first();
        return view('edit',compact(['data']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request);

        $data = company::where('id',$id)->first();

        if($request->hasFile('logo')){
        
            $destination = 'uploads/'.$data->logo;

            // dd($destination);

            if(File::exists($destination)){

                File::delete($destination);
            }
            
            $filename = $request->name.'.'.$request->file('logo')->getClientOriginalExtension();
            $request->logo =  $filename;
            
            $file = $request->file('logo');
            $file->move('uploads/', $filename);
            
        }else{
            
            $request->logo = $data->logo;
        }

        company::where('id',$id)->update([
            'name' => $request->name,
            'email' => $request->email,
            'link' => $request->link,
            'logo' => $request->logo,
        ]);

        return redirect(route('company.index'))->with('success', 'Data company telah berjaya diKemaskini');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = company::where('id',$id)->first();
        // dd($data);
        $data->delete();

        return redirect(route('company.index'))->with('success', 'Data company berjaya diPadamkan');

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/add.blade.php
<x-app-layout>
    <div class="card col-lg-6 mx-auto mt-2">
        <div class="card-body ">

            <form action="{{ url('/company') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-8">
                        <h6 class="uppercase text-gray-400">Company information</h6>
                    </div>
                    <div class="col-4 text-right">
                        <button type="submit"class="btn btn-success btn-sm">Save</button>
                    </div>
                </div>
                <div class="row">
                    <div class="my-2 mx-auto w-50 max-h-3 ">
                        <img id="preview_img" src="{{url('uploads/default.jpg')}}" alt="NoPhoto" class="w-100 h-100 logoAdd">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="form-label">Name:</label>
                        <input type="text" name="name" class="form-control form-control-sm" id="name" value="{{ old('name') }}">
                        @error('name')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="col-lg-6">
                        <label for="email" class="form-label">Email:</label>
                        <input type="text" name="email" class="form-control form-control-sm" id="email" value="{{ old('email') }}">
                        @error('email')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-lg-6">
                        <label for="logo" class="form-label">Logo:</label>
                        <input type="file" name="logo" class=" form-control form-control-sm " id="logo" value="{{ old('logo') }}">
                        <p class="text-danger">*png only </p>
                        @error('logo')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="col-lg-6">
                        <label for="link" class="form-label">Website:</label>
                        <input type="text" name="link" class="form-control form-control-sm" id="link" value="{{ old('link') }}">
                        @error('link')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
            </form>
        </div>
    </div>
    @section('js')

        <script>
        
        $(document).ready( function () {

            $('#logo').change(function(){
                const file = this.files[0];
                console.log(file);
                if (file){
                let reader = new FileReader();
                reader.onload = function(event){
                    console.log(event.target.result);
                    $('#preview_img').attr('src', event.target.result);
                }
                reader.readAsDataURL(file);
                }
            });

        });

        </script>

    @stop
</x-app-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Crud') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @if (Session::has('success'))
                        <div class="w-100">
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ Session::get('success') }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                              </div>
                        </div>
                    @endif
                    <!-- Button trigger modal -->
                    <a href="{{ route('company.create') }}" type="button" class="btn btn-primary btn-sm">
                        Add new Company
                    </a>
                    
                </div>

                <div class="p-3">
                    <table id="company" class="table table-sm  table-responsive w-100">
                        <thead>
                            <tr>
                                <th class="text-left">Name</th>
                                <th class="col "></th>
                                <th class="col ">Email</th>
                                <th class="col ">Link</th>
                                <th class="col text-right"></th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    {{-- <div class="modal fade" id="edit" tabindex="-1">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title test-gray-700">Edit Company</h5>
            <button type="button" id="saveE" class="btn btn-success btn-sm">Simpan</button>
            </div>
            <div class="modal-body">
                <h6 class="uppercase text-gray-400">Company information</h6>
                <div class="row">
                    <div class="my-2 mx-auto w-50 logoH">
                        <img id="imgPreview" src="" alt="" srcset="" class="logoH">
                    </div>
                </div>
                <form action="{{ route('company.update',['id'=>'']) }}" method="patch" enctype="multipart/form-data">
                    <div class="row">
                        <input type="hidden" name="idE" class="form-control form-control-sm" id="idE">
                        <div class="col-lg-6">
                            <label for="name" class="form-label">Name:</label>
                            <input type="text" name="nameE" class="form-control form-control-sm" id="nameE">
                        </div>
                        <div class="col-lg-6">
                            <label for="email" class="form-label">Email:</label>
                            <input type="text" name="emailE" class="form-control form-control-sm" id="emailE">
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-lg-6">
                            <label for="logo" class="form-label">Logo:</label>
                            <input id="photo" type="file" name="logoE" class=" form-control form-control-sm " id="logoE" >
                            
                        </div>
                        
                        <div class="col-lg-6">
                            <label for="linkE" class="form-label">Website:</label>
                            <input type="text" name="linkE" class="form-control form-control-sm" id="linkE">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div> --}}
    @section('js')

        <script>

            var AP = [];
            var datacom = null;
            
            $(document).ready( function () {

                $.ajax({
                    'url':'/companyData',
                    'type':'POST',
                    'data':{
                        '_token': '{{ csrf_token() }}',
                    },
                    success:function(response){
                        console.table(response);
                        if(response){
                            datacom = response;
                            // AP.table.destroy();
                            AP.table =  $('#company').DataTable({
                                "data": datacom,
                                "processing":true,
                                "bLengthChange" : false,
                                "pageLength": 15,
                                "ordering": false,
                                "paging" : false,
                                "info" : false,
                                "searching":false,
                                "columns": [
                                    { "data": "logo", defaultContent: '', width: '20px', className: 'text-center',

                                        render: function ( data, type, row ) {
                                            return ` 
                                                    <img id="preview_img" src="uploads/`+data+`" alt="NoPhoto" class="rounded-3 iconimg">

                                                    `;
                                        }

                                    },
                                    { "data": "name", defaultContent: '', width: '30px', className: 'text-left'},
                                    { "data": "email", defaultContent: '', width: '30px', className: 'text-left' },
                                    { "data": "link", defaultContent: '', width: '30px', className: 'text-left' },
                                    {
                                        "data": "id",defaultContent:"" ,className: 'text-center', width: '30px',
                                        render: function ( data, type, row ) {
                                            return ` <button> 
                                                        <a href="/company/`+data+`/edit">
                                                        Edit
                                                        </a> 
                                                    </button>
                                                    <form action="/company/`+data+`" method="POST"
                                                        class="d-inline">
                                                        @csrf
                                                        @method('delete')
                                                        <button class="text-danger"
                                                            onclick="return confirm('Are you sure?')">Delete</button>
                                                    </form>
                                                    `;
                                        }

                                    },

                                ]
                            });

                            AP.table.on('click', 'button', function(){
                                AP.selected = AP.table.row($(this).parents('tr')).data();

                                console.log(AP.selected);
                                $('#idE').val(AP.selected.id);
                                $('#nameE').val(AP.selected.name);
                                $('#emailE').val(AP.selected.email);
                                $('#imgPreview').attr("src", "uploads/"+AP.selected.logo);
                                $('#linkE').val(AP.selected.link);


                            });
                        }
                    }

                });

                $('#photo').change(function(){
                    const file = this.files[0];
                    console.log(file);
                    if (file){
                    let reader = new FileReader();
                    reader.onload = function(event){
                        console.log(event.target.result);
                        $('#imgPreview').attr('src', event.target.result);
                    }
                    reader.readAsDataURL(file);
                    }
                });

            });
        
        </script>

    @stop
</x-app-layout>

resources/views/edit.blade.php
<x-app-layout>

    <div class="card col-lg-6 mx-auto mt-2">
        <div class="card-body ">

            <form action="{{ route('company.update',['company' => $data->id]) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-8">
                        <h6 class="uppercase text-gray-400">Edit Company information</h6>
                    </div>
                    <div class="col-4 text-right">
                        <button type="submit"class="btn btn-success btn-sm">Save</button>
                    </div>
                </div>
                <div class="row">
                    <div class="my-2 mx-auto w-50 max-h-3 ">
                        {{-- C:\laragon\www\2QsoftwareDevTecAss\public\uploads\default.jpg --}}
                        <img id="preview_img" src="{{url('uploads/'.$data->logo)}}" alt="NoPhoto" class="w-100 h-100 logoAdd">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="form-label">Name:</label>
                        <input type="text" name="name" class="form-control form-control-sm" id="name" value="{{ $data->name }}">
                        @error('name')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="col-lg-6">
                        <label for="email" class="form-label">Email:</label>
                        <input type="text" name="email" class="form-control form-control-sm" id="email" value="{{ $data->email }}">
                        @error('email')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-lg-6">
                        <label for="logo" class="form-label">Logo:</label>
                        <input type="file" name="logo" class=" form-control form-control-sm " id="logo">
                        <p class="text-danger">*png only </p>
                        @error('logo')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="col-lg-6">
                        <label for="link" class="form-label">Website:</label>
                        <input type="text" name="link" class="form-control form-control-sm" id="link" value="{{ $data->link }}">
                        @error('link')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
            </form>
        </div>
    </div>

    @section('js')

        <script>

            $(document).ready( function () {

                $('#logo').change(function(){
                    const file = this.files[0];
                    console.log(file);
                    if (file){
                    let reader = new FileReader();
                    reader.onload = function(event){
                        console.log(event.target.result);
                        $('#preview_img').attr('src', event.target.result);
                    }
                    reader.readAsDataURL(file);
                    }
                });

            });

        </script>

    @stop
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        <link rel="stylesheet" href="{{ asset('bootstrap/css/bootstrap5.3.0.min.css') }}">
        <link rel="stylesheet" href="{{ asset('fontawesome6.4.0/css/fontawesome.min.css') }}">

        <link href="DataTables/datatables.min.css" rel="stylesheet"/>
 
        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
        <script src="DataTables/datatables.min.js" defer></script>

    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            {{-- <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header> --}}

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
        <script src="{{ asset('jquery/jquery.min.js') }}"></script>
        <script src="{{ asset('bootstrap/js/bootstrap5.3.0.min.js') }}"></script>
        {{-- @stack('js') --}}
        @yield('js')
        
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>